// Input schemas for src/server/actions/admin/presets.ts.
//
// ExamPreset ids are hand-set by the seed ("seed-preset-trial"), so presetId is a plain
// non-empty string, never z.cuid(). Subject ids in a distribution ARE generated by
// Prisma, so those are cuids.

import { z } from "zod";

export const PRESET_NAME_MAX = 120;
export const PRESET_QUESTION_MAX = 500;
export const PRESET_MINUTES_MAX = 600;

export const ADMIN_PRESET_MESSAGES = {
  invalid: "Хүсэлт буруу байна. Хуудсаа дахин ачаална уу.",
  notFound: "Шалгалтын төрөл олдсонгүй.",
  nameRequired: "Нэр хоосон байж болохгүй.",
  nameTooLong: `Нэр ${PRESET_NAME_MAX} тэмдэгтээс хэтрэхгүй байх ёстой.`,
  questionCount: `Асуултын тоо 1-ээс ${PRESET_QUESTION_MAX} хооронд байх ёстой.`,
  timeLimit: `Хугацаа 1-ээс ${PRESET_MINUTES_MAX} минут хооронд байх ёстой.`,
  hasAttempts: (count: number) =>
    `Энэ төрлөөр ${count} шалгалт өгсөн тул устгах боломжгүй. ` +
    "Шалгалтын түүхэнд нэр нь харагдах ёстой; оронд нь идэвхгүй болгоно уу.",
} as const;

const invalid = { error: ADMIN_PRESET_MESSAGES.invalid };

const presetId = z.string(invalid).trim().min(1, invalid).max(191, invalid);

const body = {
  name: z
    .string({ error: ADMIN_PRESET_MESSAGES.nameRequired })
    .trim()
    .min(1, { error: ADMIN_PRESET_MESSAGES.nameRequired })
    .max(PRESET_NAME_MAX, { error: ADMIN_PRESET_MESSAGES.nameTooLong }),
  questionCount: z
    .int({ error: ADMIN_PRESET_MESSAGES.questionCount })
    .min(1, { error: ADMIN_PRESET_MESSAGES.questionCount })
    .max(PRESET_QUESTION_MAX, { error: ADMIN_PRESET_MESSAGES.questionCount }),
  timeLimitMin: z
    .int({ error: ADMIN_PRESET_MESSAGES.timeLimit })
    .min(1, { error: ADMIN_PRESET_MESSAGES.timeLimit })
    .max(PRESET_MINUTES_MAX, { error: ADMIN_PRESET_MESSAGES.timeLimit }),
  isActive: z.boolean(invalid),
  sortOrder: z.int(invalid).min(0, invalid).max(9999, invalid),
  /**
   * A count per subject. Subjects left at 0 are dropped, and a distribution that ends
   * up empty means "draw from the whole bank" — the same thing as sending null.
   */
  distribution: z
    .record(z.cuid(invalid), z.int(invalid).min(0, invalid).max(PRESET_QUESTION_MAX, invalid))
    .nullable()
    .transform((value) => {
      if (value === null) return null;
      const entries = Object.entries(value).filter(([, count]) => count > 0);
      return entries.length === 0 ? null : Object.fromEntries(entries);
    }),
} as const;

export const createPresetSchema = z.strictObject(body, invalid);
export type CreatePresetInput = z.input<typeof createPresetSchema>;

export const updatePresetSchema = z.strictObject({ presetId, ...body }, invalid);
export type UpdatePresetInput = z.input<typeof updatePresetSchema>;

export const setPresetActiveSchema = z.strictObject(
  { presetId, isActive: z.boolean(invalid) },
  invalid,
);
export type SetPresetActiveInput = z.input<typeof setPresetActiveSchema>;

export const deletePresetSchema = z.strictObject({ presetId }, invalid);
export type DeletePresetInput = z.input<typeof deletePresetSchema>;
